<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="hsudarshan-a01.vmware.com" failures="4" tests="6" name="createUsers" time="5.373" errors="0" timestamp="2022-09-18T17:49:05 IST">
  <testcase classname="com.sample.api.tests.UsersTests" name="createUsersTest" time="1.328">
    <failure type="java.lang.AssertionError" message="response code not matching for create user expected [400] but found [405]">
      <![CDATA[java.lang.AssertionError: response code not matching for create user expected [400] but found [405]
at com.sample.api.assertions.UsersAPIAssertions.assertCreateApiResponse(UsersAPIAssertions.java:14)
at com.sample.api.tests.UsersTests.createUsersTest(UsersTests.java:125)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- createUsersTest -->
  <testcase classname="com.sample.api.tests.UsersTests" name="createUsersTest" time="1.36">
    <failure type="java.lang.AssertionError" message="response code not matching for create user expected [207] but found [200]">
      <![CDATA[java.lang.AssertionError: response code not matching for create user expected [207] but found [200]
at com.sample.api.assertions.UsersAPIAssertions.assertCreateApiResponse(UsersAPIAssertions.java:14)
at com.sample.api.tests.UsersTests.createUsersTest(UsersTests.java:125)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- createUsersTest -->
  <testcase classname="com.sample.api.tests.UsersTests" name="createUsersTest" time="1.371">
    <failure type="java.lang.AssertionError" message="response code not matching for create user expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: response code not matching for create user expected [400] but found [200]
at com.sample.api.assertions.UsersAPIAssertions.assertCreateApiResponse(UsersAPIAssertions.java:14)
at com.sample.api.tests.UsersTests.createUsersTest(UsersTests.java:125)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- createUsersTest -->
  <testcase classname="com.sample.api.tests.UsersTests" name="createUsersTest" time="1.701">
    <failure type="java.lang.AssertionError" message="response code not matching for create user expected [207] but found [200]">
      <![CDATA[java.lang.AssertionError: response code not matching for create user expected [207] but found [200]
at com.sample.api.assertions.UsersAPIAssertions.assertCreateApiResponse(UsersAPIAssertions.java:14)
at com.sample.api.tests.UsersTests.createUsersTest(UsersTests.java:125)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- createUsersTest -->
  <testcase classname="com.sample.api.tests.UsersTests" name="createUsersTest" time="3.05"/>
  <testcase classname="com.sample.api.tests.UsersTests" name="createUsersTest" time="5.274"/>
  <testcase classname="com.sample.api.tests.UsersTests" name="getUsersTest" time="0.0">
    <ignored/>
  </testcase> <!-- getUsersTest -->
  <testcase classname="com.sample.api.tests.UsersTests" name="updateUsersTest" time="0.0">
    <ignored/>
  </testcase> <!-- updateUsersTest -->
</testsuite> <!-- createUsers -->
